[botcom] Duplicate on the server?
tldraw/tldraw pull request #4798
Opened 2024-10-26 21:51 UTC by steveruizok

This PR adds duplication on the server. The current duplicate feature required that the duplicating file be open, so duplicating other files (from the sidebar) would duplicate the current open file instead.

### Change type

- [x] `other`

2024-10-27 20:50 UTC, steveruizok commented
As with other PRs up right now, the end to end tests here will never pass because they've been replaced by the other e2e tests. Once approved, we'll need to bypass branch protections to land it.

2024-10-28 09:30 UTC, ds300 requested changes
good improvements here, love that you've started on error handling. noticed a couple of bugs but mostly looks great

2024-10-28 09:30 UTC, ds300 commented on apps/dotcom/sync-worker/src/routes/tla/duplicateFile.ts
> +		// only persists every ~30s while users are actively editing the room. If we
```suggestion
		// only persists every ~10s while users are actively editing the room. If we
```

2024-10-28 09:30 UTC, ds300 commented on apps/dotcom/sync-worker/src/utils/tla/getCurrentSerializedRoomSnapshot.ts
> +	const snapshot = worker.getCurrentSerializedSnapshot()
```suggestion
	const snapshot = await worker.getCurrentSerializedSnapshot()
```

2024-10-28 09:30 UTC, ds300 commented on apps/dotcom/sync-worker/src/utils/tla/getTldrawAppFileRecord.ts
> +}
this should probably talk to the durable object instead of the DB, to avoid potential race conditions

2024-10-28 09:30 UTC, ds300 commented on packages/sync-core/src/lib/TLSocketRoom.ts
> +	}
let's mark this as internal for now. don't want to pollute the public api with trivial helper stuff

2024-10-28 09:30 UTC, ds300 commented on apps/dotcom/client/src/tla/app/TldrawApp.ts
> +			fileStates = this.getAll('file-state').filter((r) => r.fileId === fileId)
```suggestion
			fileStates = this.getAll('file-state').filter(
				(r) => r.fileId === fileId
			)
			this.store.remove([fileId, ...fileStates.map((s) => s.id)])
		} else {
			// If not the owner, just remove the file state
			fileStates = this.getAll('file-state').filter((r) => r.fileId === fileId && r.ownerId === userId)
```

you mistakenly switched these predicates around

2024-10-28 13:51 UTC, steveruizok commented
All good! Thanks for the feedback

2024-10-28 14:01 UTC, ds300 approved these changes

2024-10-28 14:16 UTC, merged