Create a utility type for making undefined properties optional
tldraw/tldraw pull request #5011
Opened 2024-11-27 23:27 UTC by trygve-aaberge-adsk

This extracts a type used in the object validation for making all properties of an object that accepts undefined optional. This is useful when you have an object of validators (e.g. props for a shape) and want to create the typescript type for an object that will be accepted by it. With this, any of the properties that has a validator with `.optional()` will be optional in that object.

### Change type

- [ ] `bugfix`
- [ ] `improvement`
- [ ] `feature`
- [ ] `api`
- [x] `other`

### Test plan

- [ ] Unit tests
- [ ] End to end tests

### Release notes

- Expose a utility type for making undefined properties optional

2024-11-28 10:56 UTC, SomeHats requested changes
in general (and i know there are _a lot_ of counter examples in the SDK right now) we try to avoid making things that aren't related to the SDK and whiteboarding part of our public API. 

Instead of exposing this as a generic utility, what do you think about updating [`RecordPropsType`](https://github.com/tldraw/tldraw/blob/8329c84b1049d98fd94d1ff46e29901205394fea/packages/tlschema/src/recordsWithProps.ts#L20) to include this, and keeping `MakeUndefinedOptional` tagged as `@internal`?

`RecordPropsType` is the intended way of going from a props object to the typescript type for that object: https://github.com/tldraw/tldraw/blob/8329c84b1049d98fd94d1ff46e29901205394fea/apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx#L54

2024-11-28 11:18 UTC, trygve-aaberge-adsk commented
> in general (and i know there are _a lot_ of counter examples in the SDK right now) we try to avoid making things that aren't related to the SDK and whiteboarding part of our public API.

Ah, that probably makes sense.

> Instead of exposing this as a generic utility, what do you think about updating [`RecordPropsType`](https://github.com/tldraw/tldraw/blob/8329c84b1049d98fd94d1ff46e29901205394fea/packages/tlschema/src/recordsWithProps.ts#L20) to include this, and keeping `MakeUndefinedOptional` tagged as `@internal`?
> 
> `RecordPropsType` is the intended way of going from a props object to the typescript type for that object:

That would help! The only thing we're currently using `MakeUndefinedOptional` for is to wrap `RecordPropsType` like this:

```
export type InferProps<S extends RecordProps<any>> = MakeUndefinedOptional<RecordPropsType<S>>
```

2024-12-03 11:02 UTC, SomeHats commented
oh yup sorry my mistake - we can't actually export public types that reference internal ones :(

I've pushed some tweaks to this here and will land that version: https://github.com/tldraw/tldraw/pull/5055

2024-12-03 11:02 UTC, closed without merging

2024-12-03 11:22 UTC, trygve-aaberge-adsk commented
Alright, thanks!

Btw, if you prefer, feel free to push to my branch next time so you don't have to open a new PR.

2025-03-19 19:12 UTC, trygve-aaberge-adsk commented
> Instead of exposing this as a generic utility, what do you think about updating [RecordPropsType](https://github.com/tldraw/tldraw/blob/8329c84b1049d98fd94d1ff46e29901205394fea/packages/tlschema/src/recordsWithProps.ts#L20) to include this, and keeping MakeUndefinedOptional tagged as @internal?

@SomeHats: So I ran into a problem with this when we have a union of props. The old RecordPropsType could be used to transform this union, but with the new one I only get an empty object.

Example:
```
// RecordPropsType before this PR
type OldRecordPropsType<Config extends Record<string, T.Validatable<any>>> = Expand<{
  [K in keyof Config]: T.TypeOf<Config[K]>
}>

// Same as RecordPropsType currently defined in tldraw
type NewRecordPropsType<Config extends Record<string, T.Validatable<any>>> = MakeUndefinedOptional<{
  [K in keyof Config]: T.TypeOf<Config[K]>
}>

const Props1 = {
  a: T.number,
}

const Props2 = {
  b: T.string,
}

type Props1Type = OldRecordPropsType<typeof Props1 | typeof Props2>
// Resolves to:
//     type Props1Type = {
//         a: number;
//     } | {
//         b: string;
//     }

type Props2Type = NewRecordPropsType<typeof Props1 | typeof Props2>
// Resolves to:
//    type Props2Type = {}
```

2025-03-21 10:48 UTC, SomeHats commented
What's your use-case for a union of props?

For now, I'd suggest just including the relevant helper in your own code