fix(keybindings): update vscode keybindings with windows alternatives
tldraw/tldraw pull request #595
Opened 2022-02-23 18:15 UTC by parties

Update keybindings for VSCode extension with Windows alternatives.

Thanks to @steveruizok and @tyriar for pointing out the code in question.

Resolves #540 

(The contributing guide says to fill out the "Ready for Review" template but I didn't see one; my apologies if I didn't do this correctly.)

<3

2022-02-23 20:02 UTC, Tyriar requested changes

2022-02-24 18:48 UTC, parties commented on apps/vscode/extension/package.json
> +				"win": "ctrl+=",
Fixed!

2022-02-24 19:31 UTC, Tyriar approved these changes

2022-02-24 21:44 UTC, merged

2022-02-24 21:45 UTC, steveruizok commented
Thanks @parties and @Tyriar !