feat: add "Back to content" missing translation
tldraw/tldraw pull request #809
Opened 2022-07-11 12:17 UTC by ggallon

Hi,

Add "**Back to content**" missing translation in ToolsPanel.

Not being multilingual 😬. I used a translator for languages other than French.

2022-07-11 12:24 UTC, ali-alhaidary commented
Thank you @ggallon , however, you need only to update main.json and translation contributors can take over for proper translation.

2022-07-11 12:32 UTC, ggallon commented
Hi @ali-alhaidary,
Ok thanks, do you want me to restore the translations so that the contributors can take over?

2022-07-11 12:35 UTC, ali-alhaidary commented
> Hi @ali-alhaidary, Ok thanks, do you want me to restore the translations so that the contributors can take over?

I prefer so, as using google translation for RTL and Asian languages usually gives funny things :-)

2022-07-11 12:44 UTC, ggallon commented
It's good.
Yes, even in French, it can be surprising sometimes😅

2022-07-12 11:15 UTC, judicaelandria requested changes
Thanks for your contribution @ggallon

2022-07-12 11:15 UTC, judicaelandria commented on packages/tldraw/src/components/ToolsPanel/BackToContent.tsx
> +        {intl.formatMessage({ id: 'zoom.to.content' })}
If it's an html element it's better to use 
<FormattedMesssage id="zoom.to.content" />

2022-07-13 13:18 UTC, merged

2022-07-13 13:19 UTC, steveruizok commented
Thanks!

2022-07-18 22:11 UTC, ggallon commented
@steveruizok @judicaelandria 
Thanks you