Update ar.json
tldraw/tldraw pull request #859
Opened 2022-07-28 08:15 UTC by ali-alhaidary

2022-07-28 15:03 UTC, judicaelandria requested changes

2022-07-28 15:03 UTC, judicaelandria commented on packages/tldraw/src/translations/ar.json
> +    "discord": "Discord"
Why did you add it again? I removed it in your last commit
please remove it

2022-07-28 16:04 UTC, ali-alhaidary commented
@judicaelandria it is already in main.json, I should not be removedt.

2022-07-28 17:06 UTC, judicaelandria commented
Removed it from the  main and from ar, should be good!

2022-07-29 14:04 UTC, ali-alhaidary commented
@steveruizok  is it really necessary to remove:
` "github": "Github",
  "twitter": "Twitter",
  "discord": "Discord"`
from main.json ?

2022-09-07 08:18 UTC, ali-alhaidary commented
close

2022-09-07 08:18 UTC, closed without merging